"""
Neural Verification Engine — Gemini Summary Generator
=======================================================
Converts raw verification metrics into human-readable audit summaries
using Gemini's natural language capabilities.

These summaries are ONLY for UX/demo purposes.
They do NOT affect verification logic or final status.
"""

from __future__ import annotations

import logging
from typing import Any, Optional

from pydantic import BaseModel, Field

from app.gemini.gemini_client import GeminiClient, get_gemini_client

logger = logging.getLogger("neural-verification-engine.gemini.summary")


# ═══════════════════════════════════════════════════════════════════════════
# Response Models
# ═══════════════════════════════════════════════════════════════════════════

class GeminiAuditSummary(BaseModel):
    """Human-readable audit summary generated by Gemini."""
    enabled: bool = Field(..., description="Whether Gemini summary generation was active")
    narrative_summary: Optional[str] = Field(
        None, description="Human-readable paragraph summarizing the verification"
    )
    risk_narrative: Optional[str] = Field(
        None, description="Plain-language risk assessment"
    )
    recommendation: Optional[str] = Field(
        None, description="AI-generated recommendation"
    )
    source: str = "gemini_auxiliary_summary"


# ═══════════════════════════════════════════════════════════════════════════
# Generator
# ═══════════════════════════════════════════════════════════════════════════

class AuditSummaryGenerator:
    """
    Uses Gemini to generate human-readable narrative summaries
    from raw verification metrics.

    For UX/demo purposes only — does not affect verification logic.
    """

    def __init__(self) -> None:
        self._client: GeminiClient = get_gemini_client()

    def generate(self, metrics: dict[str, Any]) -> GeminiAuditSummary:
        """
        Generate a human-readable summary from verification metrics.

        Args:
            metrics: Dictionary containing verification results
                (privacy_confidence, attack_success_rate, risk_level, etc.)

        Returns:
            GeminiAuditSummary. Disabled result if Gemini is unavailable.
        """
        if not self._client.is_enabled:
            return GeminiAuditSummary(enabled=False)

        prompt = self._build_prompt(metrics)
        response = self._client.generate_json(prompt)

        if response is None:
            logger.warning("Gemini summary generation returned no result")
            return GeminiAuditSummary(enabled=True)

        try:
            return GeminiAuditSummary(
                enabled=True,
                narrative_summary=response.get("narrative_summary", None),
                risk_narrative=response.get("risk_narrative", None),
                recommendation=response.get("recommendation", None),
            )
        except Exception as e:
            logger.warning(f"Failed to parse Gemini summary response: {e}")
            return GeminiAuditSummary(enabled=True)

    def generate_quick_summary(self, metrics: dict[str, Any]) -> Optional[str]:
        """
        Generate a single-paragraph quick summary.
        Returns None if Gemini is unavailable.
        """
        if not self._client.is_enabled:
            return None

        prompt = f"""You are an AI security auditor. Summarize these neural forgetting verification results in ONE clear paragraph (2-3 sentences max).

Metrics:
- Verification Status: {metrics.get('verification_status', 'UNKNOWN')}
- Privacy Confidence: {metrics.get('privacy_confidence', 'N/A')}%
- Attack Success Rate: {metrics.get('attack_success_rate', 'N/A')}%
- Risk Level: {metrics.get('risk_level', 'UNKNOWN')}
- Leakage Probability: {metrics.get('leakage_probability', 'N/A')}

Write a professional, concise summary suitable for a security audit report. Do not use markdown formatting. Respond with ONLY the summary paragraph, nothing else."""

        return self._client.generate(prompt)

    @staticmethod
    def _build_prompt(metrics: dict[str, Any]) -> str:
        """Build the summary generation prompt for Gemini."""
        return f"""You are an AI security auditor creating a professional narrative summary of neural forgetting verification results.

VERIFICATION METRICS:
- Verification Status: {metrics.get('verification_status', 'UNKNOWN')}
- Privacy Confidence: {metrics.get('privacy_confidence', 'N/A')}%
- Attack Success Rate: {metrics.get('attack_success_rate', 'N/A')}%  
- Attacks Total: {metrics.get('attacks_total', 'N/A')}
- Attacks Succeeded: {metrics.get('attacks_succeeded', 'N/A')}
- Risk Level: {metrics.get('risk_level', 'UNKNOWN')}
- Leakage Probability: {metrics.get('leakage_probability', 'N/A')}
- Before Leakage Score: {metrics.get('before_leakage_score', 'N/A')}
- After Leakage Score: {metrics.get('after_leakage_score', 'N/A')}
- Forgetting Delta: {metrics.get('forgetting_delta', 'N/A')}

TASK: Generate a professional audit summary in three parts.

Respond ONLY with valid JSON in this exact format:
{{
  "narrative_summary": "A 2-3 sentence professional summary of the overall verification results.",
  "risk_narrative": "A 1-2 sentence plain-language risk assessment.",
  "recommendation": "A 1-2 sentence actionable recommendation."
}}"""
